---

- name: add bitcoin group
  become: yes
  group:
    name: "{{bitcoind_user}}"
    state: "present"

- name: add bitcoin user
  become: yes
  user: 
    name: "{{bitcoind_user}}" 
    shell: "/bin/false"
    comment: "bitcoind user"
    home: "{{bitcoind_data_dir}}"
    group: "{{bitcoind_user}}"
    groups: "{{bitcoind_user}}"
    append: yes

- name: create bitcoind dir
  become: yes
  file:
    path: "{{bitcoind_dir}}"
    state: "directory"
    owner: "{{bitcoind_user}}"
    group: "{{bitcoind_user}}"
    mode: 0770

- name: create bitcoind data dir
  become: yes
  file:
    path: "{{bitcoind_data_dir}}"
    state: "directory"
    owner: "{{bitcoind_user}}"
    group: "{{bitcoind_user}}"
    mode: "0770"

- name: chown files in {{bitcoind_data_dir}}
  become: yes
  file:
    path: "{{bitcoind_data_dir}}"
    state: "directory"
    recurse: "yes"
    owner: "{{bitcoind_user}}"
    group: "{{bitcoind_user}}"

- name: check to see if bitcoind is already downloaded
  stat:
    path: "/tmp/{{bitcoind_tarball}}"
  register: bitcoind_stat

- name: download bitcoind
  become: yes
  get_url:
    url: "{{bitcoind_url}}"
    dest: "/tmp"
    checksum: "sha256:{{bitcoind_sha256}}"
  when: "bitcoind_stat.stat.exists == false"
  notify: restart bitcoind

- name: unarchive bitcoind
  become: yes
  unarchive:
    remote_src: "yes"
    src: "/tmp/{{bitcoind_tarball}}"
    dest: "/tmp"

- name: install bitcoind
  become: yes
  shell: "install -m 0755 -o {{bitcoind_user}} -g {{bitcoind_user}} -t /usr/local/bin /tmp/bitcoin-{{bitcoind_version}}/bin/*"

- name: make .bitcoin dir
  become: yes
  file:
    path: "{{bitcoind_data_dir}}/.bitcoin"
    state: "directory"
    owner: "{{bitcoind_user}}"
    group: "{{bitcoind_user}}"
    mode: "0770"
  notify: restart bitcoind

- name: install bitcoin.conf
  become: yes
  template:
    src: "bitcoin.conf.j2"
    dest: "{{bitcoind_data_dir}}/bitcoin.conf"
    owner: "{{bitcoind_user}}"
    group: "{{bitcoind_user}}"
    mode: "0770"
  notify: restart bitcoind

- name: install bitcoind service
  become: yes
  template:
    src: "bitcoind.service.j2"
    dest: "/lib/systemd/system/bitcoind.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart bitcoind

- name: ensure bitcoind is started
  become: yes
  systemd: service="bitcoind" enabled="yes" state="started" daemon_reload="yes"
