- name: create external disk mountpoint
  become: yes
  file:
    path: "{{external_disk_mountpoint}}"
    state: "directory"
    owner: root
    group: root
    mode: 0775

- name: mount drive
  become: yes
  mount:
    path: "{{external_disk_mountpoint}}"
    src: "{{external_disk_device}}"
    fstype: "{{external_disk_fstype}}"
    opts: "{{external_disk_mountopts}}"
    state: "mounted"
